{% set name = "uuid6" %}
{% set version = "2025.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bb78aa300e29db89b00410371d0c1f1824e59e29995a9daa3dedc8033d1d84ec

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - setuptools >=45
    - wheel
    - setuptools_scm >=6.2
    - toml
  run:
    - python

{% set tests_to_skip = "" %}
# AssertionError: 13970222226.416412 != 13970222226.413956 within 3 places (0.0024566650390625 difference)
{% set tests_to_skip = '-k "not test_time"' %}  # [aarch64]

test:
  source_files:
    - test
  imports:
    - uuid6
  requires:
    - pytest
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v test {{ tests_to_skip }}

about:
  home: https://github.com/oittaa/uuid6-python
  summary: New time-based UUID formats which are suited for use as a database key
  description: |
    New time-based UUID formats which are suited for use as a database key.
    This module extends immutable UUID objects (the UUID class) with the functions 
    uuid6(), uuid7(), and uuid8() from the proposed IETF RFC 9562.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://github.com/oittaa/uuid6-python/blob/main/README.md
  dev_url: https://github.com/oittaa/uuid6-python

extra:
  recipe-maintainers:
    - deepsihag
    - xylar
