{% set name = "uuid6" %}
{% set version = "2024.7.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uuid6-{{ version }}.tar.gz
  sha256: 2d29d7f63f593caaeea0e0d0dd0ad8129c9c663b29e19bdf882e864bedf18fb0

build:
  script_env:
    # this is what determines the version in setup.py
    - GITHUB_REF=refs/tags/{{ version }}
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<39]

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python

test:
  source_files:
    - test
  imports:
    - uuid6
  requires:
    - importlib
    - pip
  commands:
    - pip check
    # make sure the version reported by pip is correct
    - python -c "import importlib.metadata; assert importlib.metadata.version('{{ name }}') == '{{ version }}'"
    - pytest -vv test  # [not (aarch64 or win)]
    # skipping aarch64 and windows:
    # AssertionError: 13950139689.496391 != 13950139689.495369 within 3 places (0.0010223388671875 difference)
    - pytest -vv test -k "not test_time"  # [aarch64 or win]
  requires:
    - pip
    - pytest

about:
  home: https://github.com/oittaa/uuid6-python
  summary: New time-based UUID formats which are suited for use as a database key
  description: |
    New time-based UUID formats which are suited for use as a database key.
    This module extends immutable UUID objects (the UUID class) with the functions 
    uuid6(), uuid7(), and uuid8() from the proposed IETF RFC 9562.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://github.com/oittaa/uuid6-python/blob/main/README.md
  dev_url: https://github.com/oittaa/uuid6-python

extra:
  recipe-maintainers:
    - deepsihag
    - xylar
