{% set name = "uuid6" %}
{% set version = "2023.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/uuid6-{{ version }}.tar.gz
  sha256: 03cb97f25ca7b0ac4bea2b3a205f66bfe7f58d3b179bb0f76e1d7946446b6133

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8

test:
  imports:
    - uuid6
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/oittaa/uuid6-python
  summary: New time-based UUID formats which are suited for use as a database key
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - deepsihag
